service: genderbiasremover
plugins:
  - serverless-deployment-bucket
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.ts
    packager: 'npm'
    includeModules:
      forceExclude:
        - aws-sdk # Included in the Lambda environment already
    packagerOptions:
      scripts:
        - rimraf node_modules/aws-sdk   

provider:
  name: aws
  runtime: nodejs16.x
  stackName: genderbiasremover
  stage: prod
  region: eu-west-1
  versionFunctions: false
  deploymentBucket: 
    name: genderbiasremover-deployments
  iam:
    role:
      name: GenderBiasRemoverServerlessRole
      path: /
      managedPolicies:
        - arn:aws:iam::aws:policy/CloudFrontFullAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
  environment:    
    OPENAI_KEY: ${param:openaikey, 'NONE'}

functions:

  process-text:
    handler: process-text.main
    timeout: 120
    url:
      cors: true